import { createSelector } from "@reduxjs/toolkit";
export const user = (state) => state.rootState.user;
export const loading = (state) => state.rootState.loading;
export const sizeWindown = (state) => state.rootState.size;
export const element = (state) => state.element.data;
export const root = (state) => state.element.root;
export const domId = (state) => state.element.domId;
export const styleC = (state) => state.element.style;
export const path = (state) => state.node.path;
export const file = (state) => state.node.file;
