#server.port=8081
#spring.webjars.prefix=/webjars
#spring.webjars.enabled=true
spring:
  profiles:
    active: dev

#configDatabase
#
#spring.datasource.url=jdbc:mysql://localhost:3306/server_test?serverTimezone=UTC
#spring.datasource.username=root
#spring.datasource.password=manh2001
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#jpa configuration
#
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.show-sql=false
#spring.jpa.properties.hibernate.format_sql=true

#config jwt
#lgo.app.jwtSecret= lgohust
#lgo.app.jwtExpirationMs= 86400000

#spring.thymeleaf.template-resolver-order=0
