server:
  port: 8086

spring:
  datasource:
    username: root
    password: AZalagWnkXnJ3dgkfTqq
    url: jdbc:mysql://containers-us-west-209.railway.app:7924/lgo_database?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: lgo.tech.app@gmail.com
    password: suddouhvekiadzmo
    protocol: smtp
    properties:
        mail:
          smtp:
            auth: true
            starttls.enable: true

lgo:
  url: http://localhost:3000
  app:
    jwtSecret: lgohust
    jwtExpirationMs: 86400000


